export const FETCH_ARTIST_PENDING = 'FETCH_ARTIST_PENDING'
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS'
export const FETCH_ARTIST_FAILED = 'FETCH_ARTIST_FAILED'

export const FETCH_ALBUMS_PENDING = 'FETCH_ALBUMS_PENDING'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_FAILED = 'FETCH_ALBUMS_FAILED'

export const ADD_ALBUM_TO_PLAYLIST = 'ADD_ALBUM_TO_PLAYLIST'
export const PLAY_TRACK = 'PLAY_TRACK'
